<a href="https://colab.research.google.com/github/juvowen/AlgoTrading/blob/main/KellyCriterion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KELLY CRITERION

 is a mathematical formula used to determine the optimal size of a series of bets or investments to maximize long-term wealth growth

In [ ]:
#fake numbers for spy

mean_annual_ret =  0.1123
annual_stddev = 0.1691
risk_free_rate= 0.04

excess_ret =  mean_annual_ret - risk_free_rate
sharpe = excess_ret / annual_stddev

kelly_optimal_leverage = excess_ret /  (annual_stddev ** 2)

In [ ]:
g = excess_ret + (sharpe**2) / 2

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

In [ ]:
df = yf.download(['AAPL','NFLX','GOOG'], start='2020-01-01',end='2025-09-09')
df.dropna(inplace=True)
df

/tmp/ipykernel_5744/3553607046.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(['AAPL','NFLX','GOOG'], start='2020-01-01',end='2025-09-09')
[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL        GOOG        NFLX        AAPL        GOOG
Date
2020-01-02   72.271561   67.726997   32.980999   72.331717   67.765134
2020-01-03   71.568901   67.394661   32.590000   72.326866   67.981109
2020-01-06   72.139198   69.056427   33.583000   72.177699   69.169847
2020-01-07   71.799927   69.013321   33.075001   72.403889   69.491292
2020-01-08   72.954910   69.557182   33.925999   73.255691   69.916775
...                ...         ...         ...         ...         ...
2025-09-02  228.874542  211.249222  121.411003  230.000388  211.626895
2025-09-03  237.592346  230.292465  122.617996  237.970953  230.990016
2025-09-04  238.897522  231.847015  125.748001  239.017075  231.956632
2025-09-05  238.807846  234.348221  124.382004  240.431852  235.304873
2025-09-08  237.004517  233.550308  124.475998  239.266151  237.779259

Price                          Low                                Open  \
Ticker            NFLX        AAPL        GOOG        NFLX        AAPL
Date
2020-01-02   32.998001   71.029938   66.448110   32.478001   71.282590
2020-01-03   32.986000   71.345122   66.645954   32.553001   71.501527
2020-01-06   33.636002   70.442799   66.866665   32.119999   70.693051
2020-01-07   33.669998   71.580958   68.866707   33.029999   72.148828
2020-01-08   34.270000   71.503945   68.889503   33.105000   71.503945
...                ...         ...         ...         ...         ...
2025-09-02  121.540001  226.134663  206.236800  118.279999  228.406271
2025-09-03  122.699997  233.497472  224.333350  120.337997  236.336989
2025-09-04  125.748001  235.868717  225.967623  122.308998  237.572415
2025-09-05  126.709999  237.612266  231.567977  123.902000  239.116703
2025-09-08  125.204002  235.470176  233.121420  123.199997  238.419289

Price                                  Volume
Ticker            GOOG        NFLX       AAPL      GOOG      NFLX
Date
2020-01-02   66.448110   32.610001  135480400  28132000  44858000
2020-01-03   66.760667   32.678001  146322800  23728000  38069000
2020-01-06   66.866665   32.312000  118387200  34646000  56631000
2020-01-07   69.241166   33.646999  108872000  30054000  47032000
2020-01-08   68.950917   33.148998  132079200  30560000  71045000
...                ...         ...        ...       ...       ...
2025-09-02  208.259705  119.699997   44075600  28900100  23033000
2025-09-03  225.688599  120.514000   66427800  72250300  24715000
2025-09-04  229.350764  122.320000   47549400  32196000  30235000
2025-09-05  231.846997  126.000000   54870400  26127700  23797000
2025-09-08  235.176054  124.853996   48999500  23128800  19151000

[1428 rows x 15 columns]

In [ ]:
Returns = df['Close'].pct_change().dropna()
Returns

Ticker          AAPL      GOOG      NFLX
Date
2020-01-03 -0.009722 -0.004907 -0.011855
2020-01-06  0.007969  0.024657  0.030469
2020-01-07 -0.004703 -0.000624 -0.015127
2020-01-08  0.016086  0.007881  0.025729
2020-01-09  0.021241  0.011044 -0.010611
...              ...       ...       ...
2025-09-02 -0.010425 -0.007212  0.004850
2025-09-03  0.038090  0.090146  0.009941
2025-09-04  0.005493  0.006750  0.025526
2025-09-05 -0.000375  0.010788 -0.010863
2025-09-08 -0.007551 -0.003405  0.000756

[1427 rows x 3 columns]

In [ ]:
excess_returns = Returns - (0.04/252) #returns over risk-free rate
excess_returns

Ticker          AAPL      GOOG      NFLX
Date
2020-01-03 -0.009881 -0.005066 -0.012014
2020-01-06  0.007810  0.024499  0.030311
2020-01-07 -0.004862 -0.000783 -0.015285
2020-01-08  0.015927  0.007722  0.025571
2020-01-09  0.021082  0.010886 -0.010770
...              ...       ...       ...
2025-09-02 -0.010584 -0.007371  0.004691
2025-09-03  0.037931  0.089987  0.009783
2025-09-04  0.005335  0.006592  0.025368
2025-09-05 -0.000534  0.010629 -0.011022
2025-09-08 -0.007710 -0.003564  0.000597

[1427 rows x 3 columns]

In [ ]:
M = 252 * excess_returns.mean()
M

Ticker
AAPL    0.221926
GOOG    0.231579
NFLX    0.296179
dtype: float64

In [ ]:
C = 252*excess_returns.cov()
C

Ticker      AAPL      GOOG      NFLX
Ticker
AAPL    0.104604  0.066696  0.063890
GOOG    0.066696  0.105779  0.063323
NFLX    0.063890  0.063323  0.196525

In [ ]:
F = np.dot(np.linalg.inv(C),M)
F

#.88X leverag on APPL
#1.11X on google
##1.44x leverage on NLFX

array([0.88423208, 1.1171135 , 0.85966227])

In [ ]:
S = np.sqrt(np.dot(F.T,np.dot(C,F)))
S
#sharp ratio

np.float64(0.8423466644339187)